name: Mypy
on: [pull_request, workflow_dispatch]
jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'pip'
      - run: python -m pip install -r requirements.txt
      - name: Install mypy
        run: pip install mypy
      - name: Run mypy
        run: |
          wget -O libtorrent.pyi https://github.com/arvidn/libtorrent/raw/master/bindings/python/libtorrent/__init__.pyi
          mypy -p src.tribler.core
